version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: dance-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dance
      MYSQL_USER: dance
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--init-connect=SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
      ]
volumes:
  mysql_data:
